Repository chingu-voyages/v43-tier3-team-36, pull requests merged in 2023-04, with the labels that each got.

#100 Feature/issue 94/add collection and trade offer to user/backend
  packages/backend/src/controllers/collection.controller.ts
  packages/backend/src/controllers/user.controller.ts
  packages/backend/src/services/collection.service.ts
  packages/backend/src/services/user.service.ts
Labels: be

#116 Feature/issue 114/fetch user with id/backend
  packages/backend/src/controllers/user.controller.ts
  packages/backend/src/routes/v1/user.route.ts
Labels: be

#107 feat(components): added Loader component
  packages/frontend/src/components/common/Loader/Loader.tsx
  packages/frontend/src/components/common/Loader/Spinner.tsx
  packages/frontend/src/components/common/Loader/index.ts
  packages/frontend/tailwind.config.js
Labels: enhancement, fe

#119 Test/add cypress tests 1
  packages/frontend/cypress.config.ts
  packages/frontend/cypress/e2e/0100-authPages.cy.ts
  packages/frontend/cypress/e2e/example.cy.ts
  packages/frontend/cypress/support/commands.ts
  packages/frontend/cypress/support/index.d.ts
Labels: fe

#122 Refactor/explore offers 1
  packages/frontend/src/api/index.ts
  packages/frontend/src/components/explore/ExploreCollectors/ExploreOffers.tsx
  packages/frontend/src/components/explore/ExploreCollectors/Offers.tsx
  packages/frontend/src/components/explore/ExploreOffers/ExploreOffers.tsx
  packages/frontend/src/components/explore/ExploreOffers/Offers.tsx
  packages/frontend/src/components/explore/ExploreOffers/index.ts
  packages/frontend/src/pages/explore/offers.tsx
Labels: fe, update

#123 Feature/issue 121/trade request notification/backend
  package-lock.json
  packages/backend/package.json
  packages/backend/prisma/migrations/20230331001325_init/migration.sql
  packages/backend/prisma/migrations/20230405182030_init/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/src/app.ts
  packages/backend/src/controllers/collection.controller.ts
  packages/backend/src/routes/v1/collection.route.ts
  packages/backend/src/services/collection.service.ts
  packages/backend/src/utils/customValidation.ts
  packages/types/generated/inputTypeSchemas/TradeOfferScalarFieldEnumSchema.ts
  packages/types/generated/inputTypeSchemas/TradeRequestScalarFieldEnumSchema.ts
  packages/types/generated/inputTypeSchemas/TradeRequestStatusSchema.ts
  packages/types/generated/inputTypeSchemas/index.ts
  packages/types/generated/modelSchema/TradeOfferSchema.ts
  packages/types/generated/modelSchema/TradeRequestSchema.ts
  packages/types/generated/modelSchema/index.ts
  yarn.lock
Labels: be

#130 Feature/issue 15/exchange/buy/sell/backend
  packages/backend/prisma/migrations/20230411171330_init/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/src/controllers/collection.controller.ts
  packages/backend/src/controllers/user.controller.ts
  packages/backend/src/routes/v1/collection.route.ts
  packages/backend/src/services/collection.service.ts
  packages/types/generated/inputTypeSchemas/PushNotificationScalarFieldEnumSchema.ts
  packages/types/generated/inputTypeSchemas/index.ts
  packages/types/generated/modelSchema/CollectionItemSchema.ts
  packages/types/generated/modelSchema/PushNotificationSchema.ts
  packages/types/generated/modelSchema/TradeOfferSchema.ts
  packages/types/generated/modelSchema/TradeRequestSchema.ts
  packages/types/generated/modelSchema/UserSchema.ts
  packages/types/generated/modelSchema/index.ts
Labels: be

#140 Fix/frontend bugs 1
  packages/frontend/src/api/index.ts
  packages/frontend/src/components/auth/AuthSignup/index.ts
Labels: bug, fe

#156 feat(user service): fix error in backend code
  packages/backend/src/services/user.service.ts
Labels: be
